### ISSUE TITLE
Verbose v-bind syntax

### ISSUE THREAD

**Issue by capsur** [zwenza/spacexnow#2]
You could get rid of the verbose `v-bind:` syntax, for example used here: https://github.com/zwenza/vuespace/blob/4b21755d0fdaeb1e14a6d77a22c5faa64f55c2fc/src/components/space/AgencyList.vue#L6 with just `:key`

See https://vuejs.org/v2/guide/syntax.html#v-bind-Shorthand

**Comment by zwenza** [comment]
hi @capsur thanks for your input.
I just created a PR regarding your change!

Could you be so kind and review my changes?

**Comment by zwenza** [comment]
fixed

**Comment by capsur** [comment]
@zwenza nice, keep up the great work
